wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.17.4
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1723557883
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 98
      - 105
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 75
      - 98
      - 105
      3:
      - 23
      4: 3.11.3
      5: 0.17.4
      6: 4.43.4
      8:
      - 5
      13: linux-x86_64
