OPENAI = "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"
DB_HOST = "ec2-user-postgres-1"
DB_USER = "root"
DB_PASS = "root"
DB_NAME = "llm4adr"
GEMINI = "AIzaSyClieTww6FxrSdI8FmNL9Gg0BNVjXlWCKc"
HF_TOKEN = "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"
HF_MODEL_FINE_TUNED_GEMMA = "https://v9yidrto572ruezq.us-east-1.aws.endpoints.huggingface.cloud"
HF_MODEL_NOVEL_ONE = "https://b2w8w5mmlr342ulg.us-east-1.aws.endpoints.huggingface.cloud"
HF_MODEL_NOVEL_TWO = "https://d5agr5wf2t83nl8c.us-east-1.aws.endpoints.huggingface.cloud"
NOVEL = "FlanT5, Llama"